// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const USER_AUTH = 'USER_AUTH';
export const USER_AUTH_SUCESS = 'USER_AUTH_SUCESS'; // Get Info User
export const CHANGE_USER_PROFILE = 'CHANGE_USER_PROFILE';
export const CHANGE_USER_PROFILE_SUCCESS = 'CHANGE_USER_PROFILE_SUCCESS';
export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';
export const CHANGE_USER_AVATAR = 'CHANGE_USER_AVATAR';
export const CHANGE_USER_EMAIL = 'CHANGE_USER_EMAIL';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'signin_github_user_success';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';

//Sticky
export const GET_STICKY = 'GET_STICKY';
export const NOTES_UPDATE = 'NOTES_UPDATE';
export const FETCH_ALL_NOTES_SUCCESS = 'FETCH_ALL_NOTES_SUCCESS';
export const UPDATE_ALL_NOTES_SUCCESS = 'UPDATE_ALL_NOTES_SUCCESS';

//Contact
export const GET_All_CONTACT_SUCCESS = 'GET_All_CONTACT_SUCCESS';
export const ON_ADD_CONTACT_SUCCESS = 'ON_ADD_CONTACT_SUCCESS';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';

// User
export const GET_ALL_USER = 'GET_ALL_USER';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';
export const CHANGE_USER_INFORMATION = 'CHANGE_USER_INFORMATION';
export const HIDE_LOADING = 'HIDE_LOADING';

export const GET_ALL_REPORTTYPE = 'GET_ALL_REPORTTYPE';
export const GET_ALL_REPORTTYPE_SUCCESS = 'GET_ALL_REPORTTYPE_SUCCESS';
export const ADD_REPORTTYPE = 'ADD_REPORTTYPE';
export const ADD_REPORTTYPE_SUCCESS = 'ADD_REPORTTYPE_SUCCESS';
export const EDIT_REPORTTYPE = 'EDIT_REPORTTYPE';
export const DELETE_REPORTTYPE = 'DELETE_REPORTTYPE';
export const CHANGE_REPORTTYPE_INFORMATION = 'CHANGE_REPORTTYPE_INFORMATION';
export const HIDE_LOADING_REPORTTYPE = 'HIDE_LOADING_REPORTTYPE';

export const GET_ALL_REPORT = 'GET_ALL_REPORT';
export const GET_ALL_REPORT_SUCCESS = 'GET_ALL_REPORT_SUCCESS';
export const ADD_REPORT = 'ADD_REPORT';
export const ADD_REPORT_SUCCESS = 'ADD_REPORT_SUCCESS';
export const EDIT_REPORT = 'EDIT_REPORT';
export const DELETE_REPORT = 'DELETE_REPORT';
export const CHANGE_REPORT_INFORMATION = 'CHANGE_REPORT_INFORMATION';
export const HIDE_LOADING_REPORT = 'HIDE_LOADING_REPORT';

export const GET_ALL_POST = 'GET_ALL_POST';
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS';
export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';
export const CHANGE_POST_INFORMATION = 'CHANGE_POST_INFORMATION';
export const HIDE_LOADING_POST = 'HIDE_LOADING_POST';

// Singer
export const GET_ALL_SINGER = 'GET_ALL_SINGER';
export const GET_ALL_SINGER_SUCCESS = 'GET_ALL_SINGER_SUCCESS';
export const ADD_SINGER = 'ADD_SINGER';
export const EDIT_SINGER = 'EDIT_SINGER';
export const DELETE_SINGER = 'DELETE_SINGER';
export const HIDDEN_LOADING_SINGER = 'HIDDEN_LOADING_SINGER';

// AUTHOR
export const GET_ALL_AUTHOR = 'GET_ALL_AUTHOR';
export const GET_ALL_AUTHOR_SUCCESS = 'GET_ALL_AUTHOR_SUCCESS';
export const ADD_AUTHOR = 'ADD_AUTHOR';
export const EDIT_AUTHOR = 'EDIT_AUTHOR';
export const DELETE_AUTHOR = 'DELETE_AUTHOR';
export const HIDDEN_LOADING_AUTHOR = 'HIDDEN_LOADING_AUTHOR';

// MUSIC
export const GET_ALL_MUSIC = 'GET_ALL_MUSIC';
export const GET_ALL_MUSIC_SUCCESS = 'GET_ALL_MUSIC_SUCCESS';
export const ADD_MUSIC = 'ADD_MUSIC';
export const EDIT_MUSIC = 'EDIT_MUSIC';
export const DELETE_MUSIC = 'DELETE_MUSIC';
export const HIDDEN_LOADING_MUSIC = 'HIDDEN_LOADING_MUSIC';

// ALBUM
export const GET_ALL_ALBUM = 'GET_ALL_ALBUM';
export const GET_ALL_ALBUM_SUCCESS = 'GET_ALL_ALBUM_SUCCESS';
export const ADD_ALBUM = 'ADD_ALBUM';
export const EDIT_ALBUM = 'EDIT_ALBUM';
export const DELETE_ALBUM = 'DELETE_ALBUM';
export const HIDDEN_LOADING_ALBUM = 'HIDDEN_LOADING_ALBUM';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

// Permission
export const GET_ALL_PERMISSION = 'GET_ALL_PERMISSION';
export const GET_ALL_PERMISSION_SUCCESS = 'GET_ALL_PERMISSION_SUCCESS';
export const REMOVE_PERMISSION = 'REMOVE_PERMISSION';
export const REMOVE_PERMISSION_SUCCESS = 'REMOVE_PERMISSION_SUCCESS';
export const EDIT_PERMISSION = 'EDIT_PERMISSION';
export const EDIT_PERMISSION_SUCCESS = 'EDIT_PERMISSION_SUCCESS';
export const ADD_NEW_PERMISSION = 'ADD_NEW_PERMISSION';
export const ADD_NEW_PERMISSION_SUCCESS = 'ADD_NEW_PERMISSION_SUCCESS';

// StdCodeAuth
export const GET_STDCODEAUTH = ' GET_STDCODEAUTH';
export const GET_STDCODEAUTH_SUCCESS = ' GET_STDCODEAUTH_SUCCESS';

//Common

export const SET_EXCEL_DATA = 'SET_EXCEL_DATA';

export const REMOVE_TAB_NAVIGATION = 'REMOVE_TAB_NAVIGATION';
